variables:
  IMAGE_NAME: 'git.kytesoft.com:5050/kytesoft-web-common/teapoz'
  DEPLOYMENT: 'teapoz'
  NAMESPACE: 'onbuy'
  CONTAINER_NAME: 'teapoz'
  CI_DEBUG_SERVICES: trace
  GIT_STRATEGY: clone

stages:
  - build
  - deploy

build:dev:
  stage: build

  rules:
    - if: $CI_COMMIT_TAG =~ /^develop/
      when: always
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" git.kytesoft.com:5050
  script:
    - tag=$CI_COMMIT_TAG
    - version=${tag//develop#/}
    - docker build -t $IMAGE_NAME:$version .
    - docker push $IMAGE_NAME:$version
    - docker rmi $IMAGE_NAME:$version
    - echo 'push image success'
  tags:
    - develop

deploy:dev:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^develop/
      when: always
  before_script:
    - tag=$CI_COMMIT_TAG
    - version=${tag//develop#/}
  script:
    - kubectl set image deployment/$DEPLOYMENT $CONTAINER_NAME=$IMAGE_NAME:$version -n $NAMESPACE
    - echo 'deploy success'
  tags:
    - develop
