export const PAYMENT_METHOD = [
  {
    name: 'Direct bank transfer',
    description:
      'Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.',
  },
  {
    name: ' Check payments',
    description:
      'Please send a check to Store Name, Store Street, Store Town, Store State / County, Store Postcode.',
  },
  { name: 'Cash on delivery', description: 'Pay with cash upon delivery.' },
];

export const COUNTRIES = [
  { country: 'Afghanistan', state: 'Afghanistan 1' },
  { country: 'Albania', state: 'Albania 1' },
  { country: 'Algeria', state: 'Algeria 1' },
  { country: 'Andorra', state: 'Andorra 1' },
  { country: 'Angola', state: 'Angola 1' },
  { country: 'Anguilla', state: 'Anguilla 1' },
  { country: 'Antigua & Barbuda', state: 'Antigua & Barbuda 1' },
  { country: 'Argentina', state: 'Argentina 1' },
  { country: 'Armenia', state: 'Armenia 1' },
  { country: 'Aruba', state: 'Aruba 1' },
  { country: 'Australia', state: 'Australia 1' },
  { country: 'Austria', state: 'Austria 1' },
  { country: 'Azerbaijan', state: 'Azerbaijan 1' },
  { country: 'Bahamas', state: 'Bahamas 1' },
  { country: 'Bahrain', state: 'Bahrain 1' },
  { country: 'Bangladesh', state: 'Bangladesh 1' },
  { country: 'Barbados', state: 'Barbados 1' },
  { country: 'Belarus', state: 'Belarus 1' },
  { country: 'Belgium', state: 'Belgium 1' },
  { country: 'Belize', state: 'Belize 1' },
  { country: 'Benin', state: 'Benin 1' },
  { country: 'Bermuda', state: 'Bermuda 1' },
  { country: 'Bhutan', state: 'Bhutan 1' },
  { country: 'Bolivia', state: 'Bolivia 1' },
  { country: 'Bosnia & Herzegovina', state: 'Bosnia & Herzegovina 1' },
  { country: 'Botswana', state: 'Botswana 1' },
  { country: 'Brazil', state: 'Brazil 1' },
  { country: 'British Virgin Islands', state: 'British Virgin Islands 1' },
  { country: 'Brunei', state: 'Brunei 1' },
  { country: 'Bulgaria', state: 'Bulgaria 1' },
  { country: 'Burkina Faso', state: 'Burkina Faso 1' },
  { country: 'Burundi', state: 'Burundi 1' },
  { country: 'Cambodia', state: 'Cambodia 1' },
  { country: 'Cameroon', state: 'Cameroon 1' },
  { country: 'Canada', state: 'Canada 1' },
  { country: 'Cape Verde', state: 'Cape Verde 1' },
  { country: 'Cayman Islands', state: 'Cayman Islands 1' },
  { country: 'Central Arfrican Republic', state: 'Central Arfrican Republic 1' },
  { country: 'Chad', state: 'Chad 1' },
  { country: 'Chile', state: 'Chile 1' },
  { country: 'China', state: 'China 1' },
  { country: 'Colombia', state: 'Colombia 1' },
  { country: 'Congo', state: 'Congo 1' },
  { country: 'Cook Islands', state: 'Cook Islands 1' },
  { country: 'Costa Rica', state: 'Costa Rica 1' },
  { country: 'Cote D Ivoire', state: 'Cote D Ivoire 1' },
  { country: 'Croatia', state: 'Croatia 1' },
  { country: 'Cuba', state: 'Cuba 1' },
  { country: 'Curacao', state: 'Curacao 1' },
  { country: 'Cyprus', state: 'Cyprus 1' },
  { country: 'Czech Republic', state: 'Czech Republic 1' },
  { country: 'Denmark', state: 'Denmark 1' },
  { country: 'Djibouti', state: 'Djibouti 1' },
  { country: 'Dominica', state: 'Dominica 1' },
  { country: 'Dominican Republic', state: 'Dominican Republic 1' },
  { country: 'Ecuador', state: 'Ecuador 1' },
  { country: 'Egypt', state: 'Egypt 1' },
  { country: 'El Salvador', state: 'El Salvador 1' },
  { country: 'Equatorial Guinea', state: 'Equatorial Guinea 1' },
  { country: 'Eritrea', state: 'Eritrea 1' },
  { country: 'Estonia', state: 'Estonia 1' },
  { country: 'Ethiopia', state: 'Ethiopia 1' },
  { country: 'Falkland Islands', state: 'Falkland Islands 1' },
  { country: 'Faroe Islands', state: 'Faroe Islands 1' },
  { country: 'Fiji', state: 'Fiji 1' },
  { country: 'Finland', state: 'Finland 1' },
  { country: 'France', state: 'France 1' },
  { country: 'French Polynesia', state: 'French Polynesia 1' },
  { country: 'French West Indies', state: 'French West Indies 1' },
  { country: 'Gabon', state: 'Gabon 1' },
  { country: 'Gambia', state: 'Gambia 1' },
  { country: 'Georgia', state: 'Georgia 1' },
  { country: 'Germany', state: 'Germany 1' },
  { country: 'Ghana', state: 'Ghana 1' },
  { country: 'Gibraltar', state: 'Gibraltar 1' },
  { country: 'Greece', state: 'Greece 1' },
  { country: 'Greenland', state: 'Greenland 1' },
  { country: 'Grenada', state: 'Grenada 1' },
  { country: 'Guam', state: 'Guam 1' },
  { country: 'Guatemala', state: 'Guatemala 1' },
  { country: 'Guernsey', state: 'Guernsey 1' },
  { country: 'Guinea', state: 'Guinea 1' },
  { country: 'Guinea Bissau', state: 'Guinea Bissau 1' },
  { country: 'Guyana', state: 'Guyana 1' },
  { country: 'Haiti', state: 'Haiti 1' },
  { country: 'Honduras', state: 'Honduras 1' },
  { country: 'Hong Kong', state: 'Hong Kong 1' },
  { country: 'Hungary', state: 'Hungary 1' },
  { country: 'Iceland', state: 'Iceland 1' },
  { country: 'India', state: 'India 1' },
  { country: 'Indonesia', state: 'Indonesia 1' },
  { country: 'Iran', state: 'Iran 1' },
  { country: 'Iraq', state: 'Iraq 1' },
  { country: 'Ireland', state: 'Ireland 1' },
  { country: 'Isle of Man', state: 'Isle of Man 1' },
  { country: 'Israel', state: 'Israel 1' },
  { country: 'Italy', state: 'Italy 1' },
  { country: 'Jamaica', state: 'Jamaica 1' },
  { country: 'Japan', state: 'Japan 1' },
  { country: 'Jersey', state: 'Jersey 1' },
  { country: 'Jordan', state: 'Jordan 1' },
  { country: 'Kazakhstan', state: 'Kazakhstan 1' },
  { country: 'Kenya', state: 'Kenya 1' },
  { country: 'Kiribati', state: 'Kiribati 1' },
  { country: 'Kosovo', state: 'Kosovo 1' },
  { country: 'Kuwait', state: 'Kuwait 1' },
  { country: 'Kyrgyzstan', state: 'Kyrgyzstan 1' },
  { country: 'Laos', state: 'Laos 1' },
  { country: 'Latvia', state: 'Latvia 1' },
  { country: 'Lebanon', state: 'Lebanon 1' },
  { country: 'Lesotho', state: 'Lesotho 1' },
  { country: 'Liberia', state: 'Liberia 1' },
  { country: 'Libya', state: 'Libya 1' },
  { country: 'Liechtenstein', state: 'Liechtenstein 1' },
  { country: 'Lithuania', state: 'Lithuania 1' },
  { country: 'Luxembourg', state: 'Luxembourg 1' },
  { country: 'Macau', state: 'Macau 1' },
  { country: 'Macedonia', state: 'Macedonia 1' },
  { country: 'Madagascar', state: 'Madagascar 1' },
  { country: 'Malawi', state: 'Malawi 1' },
  { country: 'Malaysia', state: 'Malaysia 1' },
  { country: 'Maldives', state: 'Maldives 1' },
  { country: 'Mali', state: 'Mali 1' },
  { country: 'Malta', state: 'Malta 1' },
  { country: 'Marshall Islands', state: 'Marshall Islands 1' },
  { country: 'Mauritania', state: 'Mauritania 1' },
  { country: 'Mauritius', state: 'Mauritius 1' },
  { country: 'Mexico', state: 'Mexico 1' },
  { country: 'Micronesia', state: 'Micronesia 1' },
  { country: 'Moldova', state: 'Moldova 1' },
  { country: 'Monaco', state: 'Monaco 1' },
  { country: 'Mongolia', state: 'Mongolia 1' },
  { country: 'Montenegro', state: 'Montenegro 1' },
  { country: 'Montserrat', state: 'Montserrat 1' },
  { country: 'Morocco', state: 'Morocco 1' },
  { country: 'Mozambique', state: 'Mozambique 1' },
  { country: 'Myanmar', state: 'Myanmar 1' },
  { country: 'Namibia', state: 'Namibia 1' },
  { country: 'Nauro', state: 'Nauro 1' },
  { country: 'Nepal', state: 'Nepal 1' },
  { country: 'Netherlands', state: 'Netherlands 1' },
  { country: 'Netherlands Antilles', state: 'Netherlands Antilles 1' },
  { country: 'New Caledonia', state: 'New Caledonia 1' },
  { country: 'New Zealand', state: 'New Zealand 1' },
  { country: 'Nicaragua', state: 'Nicaragua 1' },
  { country: 'Niger', state: 'Niger 1' },
  { country: 'Nigeria', state: 'Nigeria 1' },
  { country: 'North Korea', state: 'North Korea 1' },
  { country: 'Norway', state: 'Norway 1' },
  { country: 'Oman', state: 'Oman 1' },
  { country: 'Pakistan', state: 'Pakistan 1' },
  { country: 'Palau', state: 'Palau 1' },
  { country: 'Palestine', state: 'Palestine 1' },
  { country: 'Panama', state: 'Panama 1' },
  { country: 'Papua New Guinea', state: 'Papua New Guinea 1' },
  { country: 'Paraguay', state: 'Paraguay 1' },
  { country: 'Peru', state: 'Peru 1' },
  { country: 'Philippines', state: 'Philippines 1' },
  { country: 'Poland', state: 'Poland 1' },
  { country: 'Portugal', state: 'Portugal 1' },
  { country: 'Puerto Rico', state: 'Puerto Rico 1' },
  { country: 'Qatar', state: 'Qatar 1' },
  { country: 'Reunion', state: 'Reunion 1' },
  { country: 'Romania', state: 'Romania 1' },
  { country: 'Russia', state: 'Russia 1' },
  { country: 'Rwanda', state: 'Rwanda 1' },
  { country: 'Saint Pierre & Miquelon', state: 'Saint Pierre & Miquelon 1' },
  { country: 'Samoa', state: 'Samoa 1' },
  { country: 'San Marino', state: 'San Marino 1' },
  { country: 'Sao Tome and Principe', state: 'Sao Tome and Principe 1' },
  { country: 'Saudi Arabia', state: 'Saudi Arabia 1' },
  { country: 'Senegal', state: 'Senegal 1' },
  { country: 'Serbia', state: 'Serbia 1' },
  { country: 'Seychelles', state: 'Seychelles 1' },
  { country: 'Sierra Leone', state: 'Sierra Leone 1' },
  { country: 'Singapore', state: 'Singapore 1' },
  { country: 'Slovakia', state: 'Slovakia 1' },
  { country: 'Slovenia', state: 'Slovenia 1' },
  { country: 'Solomon Islands', state: 'Solomon Islands 1' },
  { country: 'Somalia', state: 'Somalia 1' },
  { country: 'South Africa', state: 'South Africa 1' },
  { country: 'South Korea', state: 'South Korea 1' },
  { country: 'South Sudan', state: 'South Sudan 1' },
  { country: 'Spain', state: 'Spain 1' },
  { country: 'Sri Lanka', state: 'Sri Lanka 1' },
  { country: 'St Kitts & Nevis', state: 'St Kitts & Nevis 1' },
  { country: 'St Lucia', state: 'St Lucia 1' },
  { country: 'St Vincent', state: 'St Vincent 1' },
  { country: 'Sudan', state: 'Sudan 1' },
  { country: 'Suriname', state: 'Suriname 1' },
  { country: 'Swaziland', state: 'Swaziland 1' },
  { country: 'Sweden', state: 'Sweden 1' },
  { country: 'Switzerland', state: 'Switzerland 1' },
  { country: 'Syria', state: 'Syria 1' },
  { country: 'Taiwan', state: 'Taiwan 1' },
  { country: 'Tajikistan', state: 'Tajikistan 1' },
  { country: 'Tanzania', state: 'Tanzania 1' },
  { country: 'Thailand', state: 'Thailand 1' },
  { country: 'Togo', state: 'Togo 1' },
  { country: 'Tonga', state: 'Tonga 1' },
  { country: 'Trinidad & Tobago', state: 'Trinidad & Tobago 1' },
  { country: 'Tunisia', state: 'Tunisia 1' },
  { country: 'Turkey', state: 'Turkey 1' },
  { country: 'Turkmenistan', state: 'Turkmenistan 1' },
  { country: 'Turks & Caicos', state: 'Turks & Caicos 1' },
  { country: 'Tuvalu', state: 'Tuvalu 1' },
  { country: 'Uganda', state: 'Uganda 1' },
  { country: 'Ukraine', state: 'Ukraine 1' },
  { country: 'United Arab Emirates', state: 'United Arab Emirates 1' },
  { country: 'United Kingdom', state: 'United Kingdom 1' },
  { country: 'United States of America', state: 'United States of America 1' },
  { country: 'Uruguay', state: 'Uruguay 1' },
  { country: 'Uzbekistan', state: 'Uzbekistan 1' },
  { country: 'Vanuatu', state: 'Vanuatu 1' },
  { country: 'Vatican City', state: 'Vatican City 1' },
  { country: 'Venezuela', state: 'Venezuela 1' },
  { country: 'Vietnam', state: 'Vietnam 1' },
  { country: 'Virgin Islands (US)', state: 'Virgin Islands (US) 1' },
  { country: 'Yemen', state: 'Yemen 1' },
  { country: 'Zambia', state: 'Zambia 1' },
  { country: 'Zimbabwe', state: 'Zimbabwe 1' },
];
